### ISSUE TITLE
对性能占用的问题

### ISSUE THREAD

**Issue by Fader10** [bilive/bilive_server#11]
我想问一下私有的弹幕服务器在普通情况下一般需要消耗多少性能（cpu，内存，带宽）

**Comment by lzghzr** [comment]
目前主服务器是阿里云的2C8G5M
用的pm2，显示CPU 6%，内存1.2G
云监控页面网络入网峰值3Mbps，出300Kbps，PPS没看到，我记得之前腾讯云报的是2000左右
________________________________

**Comment by Fader10** [comment]
那腾讯云学生机的1mbps带宽会不会出现大规模的漏监听或者其他的影响
阿里云的学生机已经拿来干其他事了

**Comment by lzghzr** [comment]
监听需要下行宽带, 所以没有影响

________________________________
发件人: Lost in TianYi <notifications@github.com>
发送时间: Monday, September 9, 2019 7:43:02 PM
收件人: bilive/bilive_server <bilive_server@noreply.github.com>
抄送: lzzr <me@lzzr.me>; Comment <comment@noreply.github.com>
主题: Re: [bilive/bilive_server] 对性能占用的问题 (#11)


那腾讯云学生机的1mbps带宽会不会出现大规模的漏监听或者其他的影响
阿里云的学生机已经拿来干其他事了

―

**Comment by Fader10** [comment]
我看了一下腾讯云的文档，上下行好像都是一样的，那如果碰到国庆这种节日还能保证监控的可用性吗

**Comment by lzghzr** [comment]
一般周末晚上都会到5Mbps, 所以上下行都是1M的话, 很难

________________________________
发件人: Lost in TianYi <notifications@github.com>
发送时间: Monday, September 9, 2019 7:50:02 PM
收件人: bilive/bilive_server <bilive_server@noreply.github.com>
抄送: lzzr <me@lzzr.me>; Comment <comment@noreply.github.com>
主题: Re: [bilive/bilive_server] 对性能占用的问题 (#11)


我看了一下腾讯云的文档，上下行好像都是一样的，那如果碰到国庆这种节日还能保证监控的可用性吗

―

**Comment by Vector000** [comment]
没记错的话 tx云10M及以上对等，10M以下都是入站10M，我觉得还行？

**Comment by Fader10** [comment]
文档说的是10m一下出站10m，cvm文档
