### ISSUE TITLE
阿里云搭建服务器连接出错

### ISSUE THREAD

**Issue by 962978926** [bilive/bilive_server#12]
服务器按照步骤搭建，并开放了20080的tcp端口。抽奖监控正常，但本地连接时却报错401。
![Snipaste_2019-08-07_19-40-53](https://user-images.githubusercontent.com/23065718/62620857-f0cb0200-b94c-11e9-8c95-34cb8e0b0b43.png)

**Comment by lzghzr** [comment]
本地也用tls了吗
________________________________

**Comment by 962978926** [comment]
不太清楚，客户端在笔记本上直接用docker跑的。

**Comment by lzghzr** [comment]
恩，，，比如你客户端如果是本地的，一般填`ws://localhost:20080`
加了tls就`wss://hostname:20080`

**Comment by 962978926** [comment]
切换协议后貌似没问题了，感谢
